
USE banking;

ALTER TABLE `RoleDict` DROP FOREIGN KEY `RoleDict_fk0`;

ALTER TABLE `AccountTransaction` DROP FOREIGN KEY `AccountTransaction_fk0`;

ALTER TABLE `Job` DROP FOREIGN KEY `Job_fk0`;

ALTER TABLE `Job` DROP FOREIGN KEY `Job_fk1`;

ALTER TABLE `Job` DROP FOREIGN KEY `Job_fk2`;

ALTER TABLE `Job` DROP FOREIGN KEY `Job_fk3`;

ALTER TABLE `Job` DROP FOREIGN KEY `Job_fk4`;

ALTER TABLE `Role` DROP FOREIGN KEY `Role_fk0`;

ALTER TABLE `Role` DROP FOREIGN KEY `Role_fk1`;

ALTER TABLE `Role` DROP FOREIGN KEY `Role_fk2`;

DROP TABLE IF EXISTS `User`;

DROP TABLE IF EXISTS `UserAccountAssociation`;

DROP TABLE IF EXISTS `JobStatusDict`;

DROP TABLE IF EXISTS `PartitionDict`;

DROP TABLE IF EXISTS `QOSDict`;

DROP TABLE IF EXISTS `RoleDict`;

DROP TABLE IF EXISTS `SuperUser`;

DROP TABLE IF EXISTS `AccountTransaction`;

DROP TABLE IF EXISTS `Account`;

DROP TABLE IF EXISTS `Job`;

DROP TABLE IF EXISTS `Role`;

DROP TABLE IF EXISTS `PermDict`;

SHOW TABLES;
