# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171119_0421'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set([('accountid', 'userid')]),
        ),
    ]
