# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171119_0422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='accounttransaction',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jobstatusdict',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='qosdict',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='roledict',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='superuser',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='useraccountassociation',
            options={'managed': False},
        ),
    ]
